# Generated by Django 5.2.4 on 2025-08-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('falculty', models.CharField(max_length=100)),
                ('semester', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(max_length=100)),
                ('guardian_contact', models.CharField(max_length=15)),
                ('student_contact', models.CharField(max_length=15)),
                ('student_email', models.EmailField(max_length=254)),
                ('is_delete', models.BooleanField(default=False)),
                ('delete_time', models.DateTimeField(null=True)),
                ('deleted_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
