# Generated by Django 5.2.4 on 2025-08-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_falculty_student_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.TimeField()),
                ('is_delete', models.BooleanField(default=False)),
                ('deleted_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='delete_time',
        ),
    ]
