# Generated by Django 5.2.4 on 2025-08-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact_remove_student_delete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.TimeField(max_length=15),
        ),
    ]
